### ISSUE TITLE
graceful shutdown

### ISSUE THREAD

**Issue by firecow** [faranalytics/socketnaut#1]
Thanks for this awesome library.

My application just "hangs" after I call `net.Server close` function.

Eventually my container gets killed by the container orchestrator because it exceeds `stop_grace_period`

Do you have any tips on how I make the socketnaut service proxy do a graceful shutdown?

**Comment by adamjpatterson** [comment]
@firecow Thank you for the issue and apologies for not getting to this sooner - I just saw it now.  I will work on this over the weekend.

**Comment by adamjpatterson** [comment]
With version 1.4.0 the `ServiceProxy` has an asynchronous `shutdown` method.  

The implementation is [here](https://github.com/faranalytics/socketnaut/blob/f4870a4bc57e8912a57f5b3ac128014516528afb/src/service_proxy.ts#L348).

The documentation for the method is [here](https://github.com/faranalytics/socketnaut/tree/main?tab=readme-ov-file#serviceproxyshutdown).

Please let me know if this implementation doesn't meet your requirements.  Thanks again for submitting this issue.
